kolomiets_twig_test:
    path:     /{page}
    defaults: { _controller: KolomietsTwigBundle:Home:index, page: 1 }
    requirements:
      page: '\d+'

kolomiets_twig_homepage:
    path:     /twig
    defaults: { _controller: KolomietsTwigBundle:Home:home }
